version: 2
jobs:
  unit_test:
    docker:
      - image: circleci/node:12.16
    working_directory: ~/home
    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - run:
          name: unit test
          command: |
            npm prune
            npm install
            npm run test




workflows:
  version: 2
  unit_test:
    jobs:
      - unit_test
